AWS 17.4.4
giantswarm/releases pull request #1059
Opened 2022-11-25 11:30 UTC by njuettner

2022-11-25 13:05 UTC, njuettner commented
/test

2022-11-25 13:05 UTC, njuettner commented
/test aws-e2e
/test aws-china

2022-11-25 13:43 UTC, njuettner commented
/test aws-e2e
/test aws-china

2022-11-26 07:08 UTC, whites11 requested changes
We need to deprecate 17.4.3

2022-11-29 11:02 UTC, T-Kukawka commented
@whites11 17.4.3 deprecated

2022-11-29 11:04 UTC, T-Kukawka approved these changes

2022-11-29 11:05 UTC, whites11 approved these changes

2022-11-29 11:06 UTC, merged