Upgrade observability-bundle to 1.5.2
giantswarm/releases pull request #1325
Opened 2024-07-24 15:29 UTC by marieroque

### Checklist
- [ ] Roadmap issue created
- [ ] Release uses latest stable Flatcar
- [ ] Release uses latest Kubernetes patch version

### Triggering e2e tests

To trigger the E2E test for each new Release added in this PR add a comment with the following:

`/run releases-test-suites`

If you want to trigger conformance tests you can do so by adding a comment similar to the following:

`/run conformance-tests RELEASE_VERSION=v28.0.0 PROVIDER=capa`

For more details see the [README.md](/README.md#running-tests-against-prs)

2024-07-25 07:25 UTC, Gacko requested changes
There's an issue with a GitHub action atm that would forge a release once your PR is getting merged. I therefore block merging by requesting changes, just to be sure it's not getting merged accidentally before that issue has been fixed.

In the meantime we can run the releases test suite:

/run releases-test-suites

2024-07-25 07:27 UTC, Gacko commented
/run releases-test-suites

2024-07-25 08:50 UTC, marieroque commented
/run releases-test-suites

2024-07-25 12:07 UTC, marieroque commented
/run releases-test-suites

2024-07-26 07:08 UTC, AverageMarcus commented
The issue with getting the wrong Release should (hopefully) now be fixed...

/run releases-test-suites

2024-07-30 09:53 UTC, Gacko commented
I'm still working on fixing the automation, @marieroque. It should get merged today, then I can rebase and merge your PR also.

2024-07-30 12:14 UTC, marieroque commented
/run releases-test-suites

2024-07-30 12:56 UTC, Gacko commented on capa/v29.0.0/release.yaml
> +    - kyverno
Franco changed this to `kyverno-crds` in their PR: https://github.com/giantswarm/releases/pull/1319. I'll try to get their PR merged, so I can rebase yours afterwards.

2024-07-30 12:57 UTC, Gacko commented
/run releases-test-suites

2024-07-30 13:00 UTC, Gacko commented
/run conformance-tests RELEASE_VERSION=v29.0.0 PROVIDER=capa

2024-07-30 14:33 UTC, Gacko commented
@marieroque: I added the changelog from `observability-bundle`. Apart from that, I didn't change anything, so the passed tests should still be valid and the PR safe to skip CI.

Are my changes fine with you?

2024-07-30 14:34 UTC, Gacko commented
/run releases-test-suites

2024-07-30 14:35 UTC, Gacko approved these changes

2024-07-30 14:41 UTC, marieroque commented
> @marieroque: I added the changelog from `observability-bundle`. Apart from that, I didn't change anything, so the passed tests should still be valid and the PR safe to skip CI.
> 
> Are my changes fine with you?

Maybe we should add something related to the new default app `observability-policies` in the README

2024-07-30 15:13 UTC, Gacko commented
Sure, done! 🙂

2024-07-30 21:20 UTC, Gacko commented
I removed `observability-policies` for now for following reasons:

Even though we implemented it in the `cluster` chart, the `cluster-aws` chart does not rely on that `cluster` chart version, yet. Also, even if `cluster-aws` chart would rely on a `cluster` chart version that included the `observability-policies` app, it would not yet enable it via the corresponding provider integration values.

The same basically applies to the so called `giantswarm-cluster-suite` app. We have implemented it in the `cluster` chart, but not yet enabled it in the `cluster-aws` chart and therefore can not have it in the release for now.

To have it included in the release, we first need to release a new version of the `cluster` chart including that app and then include this new `cluster` chart version in the `cluster-aws` chart, enabling it there and afterwards release a new version of the `cluster-aws` chart.

cc @nprokopic

2024-07-30 21:40 UTC, Gacko commented
/run releases-test-suites

2024-07-30 21:40 UTC, Gacko commented
/run conformance-tests RELEASE_VERSION=v28.0.0 PROVIDER=capa

2024-07-31 04:56 UTC, Gacko commented
/run releases-test-suites

2024-07-31 04:56 UTC, Gacko commented
/run conformance-tests RELEASE_VERSION=v29.0.0 PROVIDER=capa

2024-07-31 04:59 UTC, Gacko approved these changes

2024-07-31 11:23 UTC, Gacko commented
/run releases-test-suites

2024-07-31 15:38 UTC, merged