Generate Azure v29.0.1
giantswarm/releases pull request #1389
Opened 2024-09-16 07:12 UTC by mcharriere

Signed-off-by: Matias Charriere <matias@giantswarm.io>

### Checklist

- [ ] Roadmap issue created
- [ ] Release uses latest stable Flatcar
- [ ] Release uses latest Kubernetes patch version

### Triggering E2E tests

To trigger the E2E test for each new Release added in this PR, add a comment with the following:

`/run releases-test-suites`

If you want to trigger conformance tests, you can do so by adding a comment similar to the following:

`/run conformance-tests PROVIDER=capa RELEASE_VERSION=29.1.0`

For more details see the [README.md](/README.md#running-tests-against-prs).

2024-09-16 07:55 UTC, mcharriere commented on azure/v29.0.1/README.md
> +- observability-bundle from v1.5.1 to v1.6.1
I remember that it was mentioned that we don't want to bump a minor version in a patch release, but is that so?

2024-09-16 08:02 UTC, mcharriere commented on azure/v29.0.1/README.md
> +- observability-bundle from v1.5.1 to v1.6.1
from version is wrong
```suggestion
- observability-bundle from v1.5.3 to v1.6.1
```

2024-09-16 11:09 UTC, Gacko commented
I know, this is still a WIP, but can you elaborate on why there are minor app bumps while the release itself is just a patch release? I think we went for a minor release in CAPA to bump `observability-bundle` and others in a minor step.

2024-09-16 14:40 UTC, mcharriere commented
> From the name of the PR branch I assume you're forging this mostly for updating CoreDNS. Since this is a minor bump of a v1.x.x, I'd rather head for a CAPZ v29.1.0.

Yeah, I'm fine with that. Let me rework this PR then.

2024-09-16 14:45 UTC, mcharriere commented
/run releases-test-suites

2024-09-16 18:42 UTC, mcharriere commented
This PR updates:
- coredns from v1.21.0 to v1.22.0. This is what I need.
- cert-exporter from v2.9.1 to v2.9.2. It's in `requests`.
- observability-bundle from v1.5.3 to v1.6.1. It's in `requests`.

Not sure if we want to mark v29.0.0 as deprecated in this same PR.

cc @alex-dabija

2024-09-16 21:37 UTC, Gacko reviewed
Left some suggestions. I'll check if there are any other components to update from our side tomorrow.

2024-09-16 21:37 UTC, Gacko commented on azure/v29.1.0/README.md
> +### coredns [1.22.0](https://github.com/giantswarm/coredns-app/releases/tag/v1.22.0)
```suggestion
### coredns [v1.21.0...v1.22.0](https://github.com/giantswarm/coredns-app/compare/v1.21.0...v1.22.0)
```

2024-09-16 21:37 UTC, Gacko commented on azure/v29.1.0/README.md
> +### cert-exporter [2.9.2](https://github.com/giantswarm/cert-exporter/releases/tag/v2.9.2)
```suggestion
### cert-exporter [v2.9.1...v2.9.2](https://github.com/giantswarm/cert-exporter/compare/v2.9.1...v2.9.2)
```

2024-09-16 21:37 UTC, Gacko commented on azure/v29.1.0/README.md
> +### observability-bundle [1.6.1](https://github.com/giantswarm/observability-bundle/releases/tag/v1.6.1)
```suggestion
### observability-bundle [v1.5.3...v1.6.1](https://github.com/giantswarm/observability-bundle/compare/v1.5.3...v1.6.1)
```

2024-09-16 21:37 UTC, Gacko commented on azure/v29.1.0/README.md
> +  - Bumping `grafanaAgent` to v0.4.6.
```suggestion
#### Added

- Add `alloy` v0.4.0 as `alloyMetrics`.

#### Changed

- Disable usage reporting to GrafanaLabs by:
  - Bumping `alloyLogs` and `alloyMetrics` to v0.4.1.
  - Bumping `grafanaAgent` to v0.4.6.
```

2024-09-17 07:44 UTC, alex-dabija commented
> Not sure if we want to mark v29.0.0 as deprecated in this same PR.

@mcharriere Yes, please also deprecate the v29.0.0 release because we want to maintain as few releases as possible.

2024-09-17 14:46 UTC, TheoBrigitte commented on azure/v29.1.0/release.yaml
> +    version: 1.6.1
Can we have observability-bundle v1.6.2 here ?
```suggestion
  - name: observability-bundle
    version: 1.6.2
```

2024-09-18 20:38 UTC, Gacko requested changes
Please consider [this Slack thread](https://gigantic.slack.com/archives/C02HLSDH3DZ/p1726691243035579).

Therefore I'd like to hold this PR for now so we can focus on patching older releases and get this PR here aligned to the existing CAPA v29.1.0 release afterwards. Probably next week.

2024-09-24 20:12 UTC, Gacko commented
/run releases-test-suites PREVIOUS_RELEASE=29.0.0

2024-09-24 20:15 UTC, Gacko approved these changes

2024-09-24 20:16 UTC, Gacko commented
I introduced the mentioned changes to the others apps, especially `cluster-aws`, which ships some important fixes, Kubernetes and Flatcar.

See the `README.md` and `release.diff` for what changes compared to v29.0.0.

2024-09-24 20:16 UTC, Gacko commented
Regarding v29.0.0 deprecation: Let's please do this in a separate PR.

2024-09-24 21:25 UTC, Gacko commented
/run releases-test-suites PREVIOUS_RELEASE=29.0.0

2024-09-25 14:39 UTC, Gacko commented
/run releases-test-suites PREVIOUS_RELEASE=29.0.0

2024-09-25 14:50 UTC, stone-z approved these changes

2024-09-26 11:37 UTC, Gacko commented
Tests are currently failing because of Teleport Kube Agent. @ssyno is already working on fixing it. We therefore crafted [this draft PR](https://github.com/giantswarm/releases/pull/1420) for testing changes. Once the app got fixed and released, we will integrate the new version in this PR here.

2024-09-26 22:11 UTC, ssyno commented
/run releases-test-suites

2024-09-26 22:11 UTC, ssyno commented
/run conformance-tests PROVIDER=capa RELEASE_VERSION=29.1.0

2024-09-26 22:58 UTC, ssyno approved these changes

2024-09-27 08:40 UTC, merged