Cilium update release 20.1.5
giantswarm/releases pull request #1429
Opened 2024-10-01 07:52 UTC by paurosello

### Checklist

- [ ] Roadmap issue created
- [ ] Release uses latest stable Flatcar
- [ ] Release uses latest Kubernetes patch version

### Triggering E2E tests

To trigger the E2E test for each new Release added in this PR, add a comment with the following:

`/run releases-test-suites`

If you want to trigger conformance tests, you can do so by adding a comment similar to the following:

`/run conformance-tests PROVIDER=capa RELEASE_VERSION=29.1.0`

For more details see the [README.md](/README.md#running-tests-against-prs).

2024-10-01 07:56 UTC, paurosello commented
/test aws

2024-10-01 07:57 UTC, paurosello commented
/test e2e region=default flavour=eni

2024-10-01 08:54 UTC, paurosello commented
/test e2e region=default flavour=eni

2024-10-01 09:06 UTC, Gacko requested changes

2024-10-01 09:06 UTC, Gacko commented on aws/v20.1.5/README.md
> +
```suggestion
```

2024-10-01 09:06 UTC, Gacko commented on aws/v20.1.5/README.md
> +
```suggestion
```

2024-10-01 09:06 UTC, Gacko commented on aws/v20.1.5/release.yaml
> +  - dependsOn:
Can we re-add the component version here?

2024-10-01 10:51 UTC, Gacko requested changes

2024-10-01 10:51 UTC, Gacko commented on aws/v20.1.5/README.md
> +#### Changed
```suggestion
#### Changed

```

I start feeling bad for these nits. 😬

2024-10-01 10:51 UTC, Gacko commented on aws/v20.1.5/release.diff
> +    version: 0.22.0                                            |     version: 0.25.1
Please also re-generate the diff with the component version re-added to the `release.yaml`.

2024-10-01 10:51 UTC, Gacko commented on aws/v20.1.5/release.diff
> +    version: 0.22.0                                            |     version: 0.25.1
IIRC you can pass the component version to the `devctl` command.

2024-10-01 12:48 UTC, Gacko approved these changes

2024-10-02 07:04 UTC, AndiDog approved these changes

2024-10-02 07:05 UTC, AndiDog commented
Please describe in the PR summary what this is about (I guess Cilium fixes?)

2024-10-02 07:09 UTC, Gacko commented
... and maybe here: https://github.com/giantswarm/releases/pull/1429/files#diff-6056b6b9756343785d02553b9bd6802bad5432c695c90d3a23184642adc80c41R3 😬

2024-10-02 07:39 UTC, merged