CAPA release 26.1.2
giantswarm/releases pull request #1442
Opened 2024-10-15 13:22 UTC by fiunchinho

### Checklist

- [ ] Roadmap issue created
- [ ] Release uses latest stable Flatcar
- [ ] Release uses latest Kubernetes patch version

### Triggering E2E tests

To trigger the E2E test for each new Release added in this PR, add a comment with the following:

`/run releases-test-suites`

If you want to trigger conformance tests, you can do so by adding a comment similar to the following:

`/run conformance-tests PROVIDER=capa RELEASE_VERSION=29.1.0`

For more details see the [README.md](/README.md#running-tests-against-prs).

2024-10-15 13:35 UTC, Gacko requested changes
Looks very good, thank you very much! Just two very small nits.

We should definitely improve `devctl`, so this gets easier. 🙂

2024-10-15 13:35 UTC, Gacko commented on capa/v26.1.2/README.md
> +# :zap: Giant Swarm Release v26.1.2 for  :zap:
```suggestion
# :zap: Giant Swarm Release v26.1.2 for CAPA :zap:
```

2024-10-15 13:35 UTC, Gacko commented on capa/v26.1.2/announcement.md
> +**Workload cluster release v25.1.2 for CAPA is available**. This release allows to have different node pools with different configuration to support legacy cgroupsv1.
```suggestion
**Workload cluster release v26.1.2 for CAPA is available**. This release allows to have different node pools with different configuration to support legacy cgroupsv1.
```

2024-10-15 13:39 UTC, Gacko approved these changes

2024-10-15 14:25 UTC, Gacko commented
/run releases-test-suites PREVIOUS_RELEASE=26.1.1

2024-10-15 15:25 UTC, fiunchinho commented
/run releases-test-suites PREVIOUS_RELEASE=26.1.1

2024-10-15 15:36 UTC, fiunchinho commented
Tests are failing because ec2 instances won't come up due to
```
failed to create AWSMachine instance: failed to find ami: found no AMIs
      with the name: "flatcar-stable-3815.2.5-kube-1.26.15-tooling-N/A-gs"
```

2024-10-16 05:13 UTC, Gacko commented
Oh, damn. This is my fault... I think `cluster-aws` v1.3.3 was forged for CAPA v27.2.0 because of the private ECR thingy. And for that to work, we needed the new image lookup format with `os-tooling`, which then got introduced in `cluster` v1.0.2.

This means we will need to build images for Kubernetes v1.25 using the new image name format. Gonna trigger them.

For consistency reasons we should probably also do a v25.2.2 then, right?

2024-10-16 07:52 UTC, Gacko commented
/run releases-test-suites PREVIOUS_RELEASE=26.1.1

2024-10-16 07:52 UTC, Gacko commented
/run releases-test-suites PREVIOUS_RELEASE=25.2.1

2024-10-16 08:07 UTC, Gacko requested changes
Ah, damn, with the latest changes in image lookup format the nodes will roll. So we need a v26.2.0.

2024-10-16 12:30 UTC, Gacko commented
Here's a PR for a v26.2.0: https://github.com/giantswarm/releases/pull/1446

2024-10-16 12:43 UTC, fiunchinho commented
Closing this one then. Thanks.

2024-10-16 12:43 UTC, closed without merging