CAPA: Release v25.1.3
giantswarm/releases pull request #1516
Opened 2024-12-10 10:42 UTC by AndiDog

Towards https://github.com/giantswarm/giantswarm/issues/31843

### Checklist

- [ ] Roadmap issue created
- [ ] Release uses latest stable Flatcar
- [ ] Release uses latest Kubernetes patch version

### Triggering E2E tests

To trigger the E2E test for each new Release added in this PR, add a comment with the following:

`/run releases-test-suites`

If you want to trigger conformance tests, you can do so by adding a comment similar to the following:

`/run conformance-tests PROVIDER=capa RELEASE_VERSION=29.1.0`

For more details see the [README.md](/README.md#running-tests-against-prs).

2024-12-10 10:43 UTC, AndiDog commented
@giantswarm/team-tenet do you want to bump cert-exporter?

2024-12-10 10:44 UTC, AndiDog commented
/run releases-test-suites

2024-12-10 10:49 UTC, Gacko requested changes

2024-12-10 10:49 UTC, Gacko commented on capa/v25.1.3/README.md
> +This release introduced aws-node-termination-handler for graceful draining of nodes during an upgrade or other type of replacement of worker nodes.
```suggestion
This release introduces `aws-node-termination-handler` for graceful draining of nodes during an upgrade or other type of replacement of worker nodes.
```

2024-12-10 10:49 UTC, Gacko commented on capa/v25.1.3/README.md
> +The behavior is now explained in the [node pools documentation](https://docs.giantswarm.io/tutorials/fleet-management/cluster-management/node-pools/#what-happens-when-rolling-nodes).
```suggestion
Details can be found in the [node pools documentation](https://docs.giantswarm.io/tutorials/fleet-management/cluster-management/node-pools/#what-happens-when-rolling-nodes).
```

2024-12-10 10:49 UTC, Gacko commented on capa/v25.1.3/README.md
> +## Changes compared to v25.1.1
```suggestion
## Changes compared to v25.1.2
```

2024-12-10 10:49 UTC, Gacko commented on capa/v25.1.3/README.md
> +- New application aws-nth-bundle ("NTH" is short for aws-node-termination-handler)
```suggestion
- New application `aws-nth-bundle` ("NTH" is short for `aws-node-termination-handler`)
```

Also I'd list this under apps.

2024-12-10 10:49 UTC, Gacko commented on capa/v25.1.3/release.yaml
> +    version: 1.1.1
```suggestion
  - name: aws-nth-bundle
    version: 1.1.1
```

`default` is already the default via CRD. Also: Are there any dependencies?

2024-12-10 10:50 UTC, Gacko commented
> @giantswarm/team-tenet do you want to bump cert-exporter?

Yep, will do so.

2024-12-10 15:16 UTC, Gacko commented
/run releases-test-suites TARGET_SUITES=./providers/capa/standard

I doesn't really make sense to test the upgrade here as this is the first version after Vintage, right?

2024-12-10 16:44 UTC, Gacko approved these changes

2024-12-10 16:45 UTC, Gacko commented
/run releases-test-suites TARGET_SUITES=./providers/capa/standard TARGET_RELEASE=aws-25.1.3

2024-12-10 16:45 UTC, Gacko commented
/run releases-test-suites TARGET_SUITES=./providers/capa/standard TARGET_RELEASES=aws-25.1.3

2024-12-10 16:53 UTC, AndiDog commented
I still need to fix the aws-node-termination-handler behavior so it reacts to dying spot instances

2024-12-11 18:10 UTC, AndiDog commented
/run releases-test-suites TARGET_SUITES=./providers/capa/standard

2024-12-11 19:00 UTC, AndiDog commented
/run releases-test-suites TARGET_SUITES=./providers/capa/standard

2024-12-12 09:35 UTC, AndiDog commented
Forgot to set the base release for the test

/run releases-test-suites PREVIOUS_RELEASE=25.1.2 TARGET_SUITES=./providers/capa/upgrade

2024-12-12 10:01 UTC, Gacko requested changes

2024-12-12 10:41 UTC, T-Kukawka approved these changes

2024-12-12 10:52 UTC, Gacko approved these changes

2024-12-12 10:55 UTC, merged