CAPZ: Release v29.4.0.
giantswarm/releases pull request #1522
Opened 2024-12-11 14:31 UTC by Gacko

### Checklist

- [x] Roadmap issue created
- [x] Release uses latest stable Flatcar
- [x] Release uses latest Kubernetes patch version

### Triggering E2E tests

To trigger the E2E test for each new Release added in this PR, add a comment with the following:

`/run releases-test-suites`

If you want to trigger conformance tests, you can do so by adding a comment similar to the following:

`/run conformance-tests PROVIDER=capa RELEASE_VERSION=29.1.0`

For more details see the [README.md](/README.md#running-tests-against-prs).

2024-12-11 15:05 UTC, njuettner approved these changes

2024-12-11 16:50 UTC, AndiDog requested changes
I'll push our cluster-aws/aws-node-termination-handler stuff here since I need a commit in order to set `E2E_RELEASE_VERSION`/`E2E_RELEASE_COMMIT` in tests. Blocking the release until we've successfully tested the feature ;)

2024-12-11 19:40 UTC, Gacko commented
I'll come up with CAPA tomorrow.

2024-12-12 13:41 UTC, Gacko commented
/run releases-test-suites PREVIOUS_RELEASE=29.3.0

2024-12-12 14:29 UTC, T-Kukawka approved these changes

2024-12-14 11:16 UTC, Gacko commented
/run releases-test-suites PREVIOUS_RELEASE=29.3.0

2024-12-14 12:06 UTC, Gacko commented
I'm skipping CI as I had to rebase this branch on top of master and don't want to run tests again just for this.

2024-12-14 12:07 UTC, Gacko commented
I'm skipping CI as I had to rebase this branch on top of master and don't want to run tests again just for this.

2024-12-14 12:14 UTC, merged